Added tests
ms1-learner/python-04-jp pull request #2
Opened 2023-08-25 07:30 UTC by dancer-yuma

# What I did

- added tests for those the instruction of which is clear enough to implement tests
- added `#` if instructions in Japanese are missing when they are to be commented out
- moved `wovendojo` to the root repository so we can import them without using unit path
- added `pytest-timeout` for one challenge so it will not get stuck to execute thousands of lines of code
- added challenges for api units

# What I did not

- fix English instructions
- add tests for api units

2023-09-08 04:38 UTC, xvarc-wp reviewed
@dancer-yuma your approach here is to make each challenge into a module so that you can access the methods inside?

2023-09-08 05:07 UTC, xvarc-wp requested changes
Please check the comments before merging 🙏

2023-09-08 05:07 UTC, xvarc-wp commented on 02_advanced-python-concepts/10_divisible_generator/data_for_test/expected_outputs.py
@dancer-yuma For questions such as these I would reduce the length and therefore the required compute of the test by testing the presence of a few of these values, or by testing the correct length of the list. It is possible we may get a few false positives but I do not think that this is a problem.

2023-09-11 04:41 UTC, dancer-yuma commented on 02_advanced-python-concepts/10_divisible_generator/data_for_test/expected_outputs.py
True, let me fix the test by checking the printed values are divisible by 11.

2023-09-11 04:51 UTC, dancer-yuma commented on 02_advanced-python-concepts/10_divisible_generator/data_for_test/expected_outputs.py
Fixed in [cad08c2](https://github.com/ms1-learner/python-04-jp/pull/2/commits/cad08c2f7fa0668f0f9f74fd7c9ae3e3a6b11455).

2023-09-11 04:51 UTC, dancer-yuma commented
@xvarc-wp 
Please review again! I fixed `test_divisible_generator` in [cad08c2](https://github.com/ms1-learner/python-04-jp/pull/2/commits/cad08c2f7fa0668f0f9f74fd7c9ae3e3a6b11455).

2023-09-11 06:28 UTC, xvarc-wp approved these changes
lgtm

2023-09-11 06:28 UTC, merged